name: 'Check Dirty Git'
description: 'Fail if there are uncommitted changes in the git working directory'
author: 'cbeck88'
branding:
  icon: 'git-commit'
  color: 'orange'

runs:
  using: composite
  steps:
    - name: Check for uncommitted changes
      shell: bash
      run: |
        # Workaround for https://github.com/actions/checkout/issues/766
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

        if [[ -n $(git status --porcelain) ]]; then
          echo "::error::Repository has uncommitted changes"
          git status
          exit 1
        fi
